### ISSUE TITLE
Issue wit Curl

### ISSUE THREAD

**Issue by EmanueleCoppola** [256cats/check-proxy#6]
I got this error with a custom file and also with the bundled client.js example:

```
node client.js 
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: dlopen(/Users/manu/Desktop/Proxy test/node_modules/node-libcurl/lib/binding/node_libcurl.node, 1): Library not loaded: /Users/travis/lib/libcurl.4.dylib
  Referenced from: /Users/manu/Desktop/Proxy test/node_modules/node-libcurl/lib/binding/node_libcurl.node
  Reason: Incompatible library version: node_libcurl.node requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/manu/Desktop/Proxy test/node_modules/node-libcurl/lib/Easy.js:40:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

```

**Comment by 256cats** [comment]
It looks like https://github.com/JCMais/node-libcurl issue.

**Comment by JCMais** [comment]
See https://github.com/JCMais/node-libcurl/issues/43

There are some linkings errors I still need to fix on the prebuilt binaries.

**Comment by 256cats** [comment]
Libcurl dependency was removed
